/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model;


import com.walker.jooq.jooqdemo.model.tables.AdminUser;
import com.walker.jooq.jooqdemo.model.tables.Authority;
import com.walker.jooq.jooqdemo.model.tables.AuthorityUser;
import com.walker.jooq.jooqdemo.model.tables.ExchangeLog;
import com.walker.jooq.jooqdemo.model.tables.ExchangeRecord;
import com.walker.jooq.jooqdemo.model.tables.ExchangeUser;
import com.walker.jooq.jooqdemo.model.tables.MoneyStatus;
import com.walker.jooq.jooqdemo.model.tables.OilCard;
import com.walker.jooq.jooqdemo.model.tables.Phone;
import com.walker.jooq.jooqdemo.model.tables.RecodeDetail;
import com.walker.jooq.jooqdemo.model.tables.UserWhite;
import com.walker.jooq.jooqdemo.model.tables.WxExchange;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>exchange</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADMIN_USER_PRIMARY = Indexes0.ADMIN_USER_PRIMARY;
    public static final Index AUTHORITY_PRIMARY = Indexes0.AUTHORITY_PRIMARY;
    public static final Index AUTHORITY_USER_PRIMARY = Indexes0.AUTHORITY_USER_PRIMARY;
    public static final Index EXCHANGE_LOG_PRIMARY = Indexes0.EXCHANGE_LOG_PRIMARY;
    public static final Index EXCHANGE_RECORD_PRIMARY = Indexes0.EXCHANGE_RECORD_PRIMARY;
    public static final Index EXCHANGE_USER_PRIMARY = Indexes0.EXCHANGE_USER_PRIMARY;
    public static final Index MONEY_STATUS_PRIMARY = Indexes0.MONEY_STATUS_PRIMARY;
    public static final Index OIL_CARD_PRIMARY = Indexes0.OIL_CARD_PRIMARY;
    public static final Index PHONE_PRIMARY = Indexes0.PHONE_PRIMARY;
    public static final Index RECODE_DETAIL_PRIMARY = Indexes0.RECODE_DETAIL_PRIMARY;
    public static final Index USER_WHITE_PRIMARY = Indexes0.USER_WHITE_PRIMARY;
    public static final Index WX_EXCHANGE_PRIMARY = Indexes0.WX_EXCHANGE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADMIN_USER_PRIMARY = Internal.createIndex("PRIMARY", AdminUser.ADMIN_USER, new OrderField[] { AdminUser.ADMIN_USER.ID }, true);
        public static Index AUTHORITY_PRIMARY = Internal.createIndex("PRIMARY", Authority.AUTHORITY, new OrderField[] { Authority.AUTHORITY.ID }, true);
        public static Index AUTHORITY_USER_PRIMARY = Internal.createIndex("PRIMARY", AuthorityUser.AUTHORITY_USER, new OrderField[] { AuthorityUser.AUTHORITY_USER.ID }, true);
        public static Index EXCHANGE_LOG_PRIMARY = Internal.createIndex("PRIMARY", ExchangeLog.EXCHANGE_LOG, new OrderField[] { ExchangeLog.EXCHANGE_LOG.ID }, true);
        public static Index EXCHANGE_RECORD_PRIMARY = Internal.createIndex("PRIMARY", ExchangeRecord.EXCHANGE_RECORD, new OrderField[] { ExchangeRecord.EXCHANGE_RECORD.ID }, true);
        public static Index EXCHANGE_USER_PRIMARY = Internal.createIndex("PRIMARY", ExchangeUser.EXCHANGE_USER, new OrderField[] { ExchangeUser.EXCHANGE_USER.ID }, true);
        public static Index MONEY_STATUS_PRIMARY = Internal.createIndex("PRIMARY", MoneyStatus.MONEY_STATUS, new OrderField[] { MoneyStatus.MONEY_STATUS.ID }, true);
        public static Index OIL_CARD_PRIMARY = Internal.createIndex("PRIMARY", OilCard.OIL_CARD, new OrderField[] { OilCard.OIL_CARD.ID }, true);
        public static Index PHONE_PRIMARY = Internal.createIndex("PRIMARY", Phone.PHONE, new OrderField[] { Phone.PHONE.ID }, true);
        public static Index RECODE_DETAIL_PRIMARY = Internal.createIndex("PRIMARY", RecodeDetail.RECODE_DETAIL, new OrderField[] { RecodeDetail.RECODE_DETAIL.ID }, true);
        public static Index USER_WHITE_PRIMARY = Internal.createIndex("PRIMARY", UserWhite.USER_WHITE, new OrderField[] { UserWhite.USER_WHITE.ID }, true);
        public static Index WX_EXCHANGE_PRIMARY = Internal.createIndex("PRIMARY", WxExchange.WX_EXCHANGE, new OrderField[] { WxExchange.WX_EXCHANGE.ID }, true);
    }
}
