/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model;


import com.walker.jooq.jooqdemo.model.tables.AdminUser;
import com.walker.jooq.jooqdemo.model.tables.Authority;
import com.walker.jooq.jooqdemo.model.tables.AuthorityUser;
import com.walker.jooq.jooqdemo.model.tables.ExchangeLog;
import com.walker.jooq.jooqdemo.model.tables.ExchangeRecord;
import com.walker.jooq.jooqdemo.model.tables.ExchangeUser;
import com.walker.jooq.jooqdemo.model.tables.MoneyStatus;
import com.walker.jooq.jooqdemo.model.tables.OilCard;
import com.walker.jooq.jooqdemo.model.tables.Phone;
import com.walker.jooq.jooqdemo.model.tables.RecodeDetail;
import com.walker.jooq.jooqdemo.model.tables.UserWhite;
import com.walker.jooq.jooqdemo.model.tables.WxExchange;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in exchange
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>exchange.admin_user</code>.
     */
    public static final AdminUser ADMIN_USER = com.walker.jooq.jooqdemo.model.tables.AdminUser.ADMIN_USER;

    /**
     * The table <code>exchange.authority</code>.
     */
    public static final Authority AUTHORITY = com.walker.jooq.jooqdemo.model.tables.Authority.AUTHORITY;

    /**
     * The table <code>exchange.authority_user</code>.
     */
    public static final AuthorityUser AUTHORITY_USER = com.walker.jooq.jooqdemo.model.tables.AuthorityUser.AUTHORITY_USER;

    /**
     * 日志表
     */
    public static final ExchangeLog EXCHANGE_LOG = com.walker.jooq.jooqdemo.model.tables.ExchangeLog.EXCHANGE_LOG;

    /**
     * 兑换记录
     */
    public static final ExchangeRecord EXCHANGE_RECORD = com.walker.jooq.jooqdemo.model.tables.ExchangeRecord.EXCHANGE_RECORD;

    /**
     * 兑换人兑换信息关联表
     */
    public static final ExchangeUser EXCHANGE_USER = com.walker.jooq.jooqdemo.model.tables.ExchangeUser.EXCHANGE_USER;

    /**
     * 面值余量提醒
     */
    public static final MoneyStatus MONEY_STATUS = com.walker.jooq.jooqdemo.model.tables.MoneyStatus.MONEY_STATUS;

    /**
     * 油卡
     */
    public static final OilCard OIL_CARD = com.walker.jooq.jooqdemo.model.tables.OilCard.OIL_CARD;

    /**
     * The table <code>exchange.phone</code>.
     */
    public static final Phone PHONE = com.walker.jooq.jooqdemo.model.tables.Phone.PHONE;

    /**
     * 兑换记录详情 包含油卡和微信记录
     */
    public static final RecodeDetail RECODE_DETAIL = com.walker.jooq.jooqdemo.model.tables.RecodeDetail.RECODE_DETAIL;

    /**
     * 领卡人白名单
     */
    public static final UserWhite USER_WHITE = com.walker.jooq.jooqdemo.model.tables.UserWhite.USER_WHITE;

    /**
     * 微信提现表
     */
    public static final WxExchange WX_EXCHANGE = com.walker.jooq.jooqdemo.model.tables.WxExchange.WX_EXCHANGE;
}
