/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model.tables;


import com.walker.jooq.jooqdemo.model.Exchange;
import com.walker.jooq.jooqdemo.model.Indexes;
import com.walker.jooq.jooqdemo.model.Keys;
import com.walker.jooq.jooqdemo.model.tables.records.WxExchangeRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 微信提现表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WxExchange extends TableImpl<WxExchangeRecord> {

    private static final long serialVersionUID = 341513102;

    /**
     * The reference instance of <code>exchange.wx_exchange</code>
     */
    public static final WxExchange WX_EXCHANGE = new WxExchange();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WxExchangeRecord> getRecordType() {
        return WxExchangeRecord.class;
    }

    /**
     * The column <code>exchange.wx_exchange.id</code>. uuid
     */
    public final TableField<WxExchangeRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "uuid");

    /**
     * The column <code>exchange.wx_exchange.order_no</code>. 微信订单号 对应payment_no
     */
    public final TableField<WxExchangeRecord, String> ORDER_NO = createField("order_no", org.jooq.impl.SQLDataType.VARCHAR(255), this, "微信订单号 对应payment_no");

    /**
     * The column <code>exchange.wx_exchange.open_id</code>. 用户对应的open_id
     */
    public final TableField<WxExchangeRecord, String> OPEN_ID = createField("open_id", org.jooq.impl.SQLDataType.VARCHAR(255), this, "用户对应的open_id");

    /**
     * The column <code>exchange.wx_exchange.create_time</code>. 兑换时间
     */
    public final TableField<WxExchangeRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "兑换时间");

    /**
     * The column <code>exchange.wx_exchange.money</code>. 兑换金额
     */
    public final TableField<WxExchangeRecord, String> MONEY = createField("money", org.jooq.impl.SQLDataType.VARCHAR(255), this, "兑换金额");

    /**
     * The column <code>exchange.wx_exchange.discount_money</code>. 折扣后金额
     */
    public final TableField<WxExchangeRecord, String> DISCOUNT_MONEY = createField("discount_money", org.jooq.impl.SQLDataType.VARCHAR(255), this, "折扣后金额");

    /**
     * The column <code>exchange.wx_exchange.service_charge</code>. 手续费
     */
    public final TableField<WxExchangeRecord, BigDecimal> SERVICE_CHARGE = createField("service_charge", org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "手续费");

    /**
     * The column <code>exchange.wx_exchange.cash_discount</code>. 微信提现折扣
     */
    public final TableField<WxExchangeRecord, Double> CASH_DISCOUNT = createField("cash_discount", org.jooq.impl.SQLDataType.DOUBLE, this, "微信提现折扣");

    /**
     * The column <code>exchange.wx_exchange.status</code>. 状态 0失败 1成功
     */
    public final TableField<WxExchangeRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态 0失败 1成功");

    /**
     * The column <code>exchange.wx_exchange.user_id</code>. 用户id
     */
    public final TableField<WxExchangeRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR(255), this, "用户id");

    /**
     * The column <code>exchange.wx_exchange.update_time</code>. 更新时间
     */
    public final TableField<WxExchangeRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>exchange.wx_exchange.partner_trade_no</code>. 商户转账订单号
     */
    public final TableField<WxExchangeRecord, String> PARTNER_TRADE_NO = createField("partner_trade_no", org.jooq.impl.SQLDataType.VARCHAR(255), this, "商户转账订单号");

    /**
     * The column <code>exchange.wx_exchange.service_charge_discount</code>. 手续费折扣
     */
    public final TableField<WxExchangeRecord, Double> SERVICE_CHARGE_DISCOUNT = createField("service_charge_discount", org.jooq.impl.SQLDataType.DOUBLE, this, "手续费折扣");

    /**
     * The column <code>exchange.wx_exchange.error_info</code>. 失败原因
     */
    public final TableField<WxExchangeRecord, String> ERROR_INFO = createField("error_info", org.jooq.impl.SQLDataType.VARCHAR(255), this, "失败原因");

    /**
     * Create a <code>exchange.wx_exchange</code> table reference
     */
    public WxExchange() {
        this(DSL.name("wx_exchange"), null);
    }

    /**
     * Create an aliased <code>exchange.wx_exchange</code> table reference
     */
    public WxExchange(String alias) {
        this(DSL.name(alias), WX_EXCHANGE);
    }

    /**
     * Create an aliased <code>exchange.wx_exchange</code> table reference
     */
    public WxExchange(Name alias) {
        this(alias, WX_EXCHANGE);
    }

    private WxExchange(Name alias, Table<WxExchangeRecord> aliased) {
        this(alias, aliased, null);
    }

    private WxExchange(Name alias, Table<WxExchangeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("微信提现表"));
    }

    public <O extends Record> WxExchange(Table<O> child, ForeignKey<O, WxExchangeRecord> key) {
        super(child, key, WX_EXCHANGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Exchange.EXCHANGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WX_EXCHANGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WxExchangeRecord> getPrimaryKey() {
        return Keys.KEY_WX_EXCHANGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WxExchangeRecord>> getKeys() {
        return Arrays.<UniqueKey<WxExchangeRecord>>asList(Keys.KEY_WX_EXCHANGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchange as(String alias) {
        return new WxExchange(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchange as(Name alias) {
        return new WxExchange(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WxExchange rename(String name) {
        return new WxExchange(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WxExchange rename(Name name) {
        return new WxExchange(name, null);
    }
}
