/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model.tables.records;


import com.walker.jooq.jooqdemo.model.tables.AuthorityUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityUserRecord extends UpdatableRecordImpl<AuthorityUserRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1201571532;

    /**
     * Setter for <code>exchange.authority_user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>exchange.authority_user.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>exchange.authority_user.authority_id</code>. 权限表id
     */
    public void setAuthorityId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>exchange.authority_user.authority_id</code>. 权限表id
     */
    public String getAuthorityId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>exchange.authority_user.user_id</code>. 管理用户id
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>exchange.authority_user.user_id</code>. 管理用户id
     */
    public String getUserId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AuthorityUser.AUTHORITY_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AuthorityUser.AUTHORITY_USER.AUTHORITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AuthorityUser.AUTHORITY_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAuthorityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAuthorityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityUserRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityUserRecord value2(String value) {
        setAuthorityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityUserRecord value3(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityUserRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorityUserRecord
     */
    public AuthorityUserRecord() {
        super(AuthorityUser.AUTHORITY_USER);
    }

    /**
     * Create a detached, initialised AuthorityUserRecord
     */
    public AuthorityUserRecord(String id, String authorityId, String userId) {
        super(AuthorityUser.AUTHORITY_USER);

        set(0, id);
        set(1, authorityId);
        set(2, userId);
    }
}
