/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model.tables.records;


import com.walker.jooq.jooqdemo.model.tables.Authority;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorityRecord extends UpdatableRecordImpl<AuthorityRecord> implements Record6<String, String, Timestamp, Timestamp, String, Integer> {

    private static final long serialVersionUID = -167073040;

    /**
     * Setter for <code>exchange.authority.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>exchange.authority.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>exchange.authority.name</code>. 权限名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>exchange.authority.name</code>. 权限名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>exchange.authority.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>exchange.authority.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>exchange.authority.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>exchange.authority.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>exchange.authority.url</code>. 前端路由地址
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>exchange.authority.url</code>. 前端路由地址
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>exchange.authority.sortId</code>. 排序字段
     */
    public void setSortid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>exchange.authority.sortId</code>. 排序字段
     */
    public Integer getSortid() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Timestamp, Timestamp, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Timestamp, Timestamp, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Authority.AUTHORITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Authority.AUTHORITY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Authority.AUTHORITY.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Authority.AUTHORITY.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Authority.AUTHORITY.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Authority.AUTHORITY.SORTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSortid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSortid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityRecord value3(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityRecord value4(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityRecord value5(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityRecord value6(Integer value) {
        setSortid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityRecord values(String value1, String value2, Timestamp value3, Timestamp value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorityRecord
     */
    public AuthorityRecord() {
        super(Authority.AUTHORITY);
    }

    /**
     * Create a detached, initialised AuthorityRecord
     */
    public AuthorityRecord(String id, String name, Timestamp createTime, Timestamp updateTime, String url, Integer sortid) {
        super(Authority.AUTHORITY);

        set(0, id);
        set(1, name);
        set(2, createTime);
        set(3, updateTime);
        set(4, url);
        set(5, sortid);
    }
}
