/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model.tables.records;


import com.walker.jooq.jooqdemo.model.tables.ExchangeLog;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeLogRecord extends UpdatableRecordImpl<ExchangeLogRecord> implements Record8<String, String, Integer, BigDecimal, Integer, Timestamp, String, String> {

    private static final long serialVersionUID = 447406231;

    /**
     * Setter for <code>exchange.exchange_log.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>exchange.exchange_log.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>exchange.exchange_log.mobile</code>. 手机号
     */
    public void setMobile(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>exchange.exchange_log.mobile</code>. 手机号
     */
    public String getMobile() {
        return (String) get(1);
    }

    /**
     * Setter for <code>exchange.exchange_log.status</code>. 状态 0失效 1有效（收益）  2兑换
     */
    public void setStatus(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>exchange.exchange_log.status</code>. 状态 0失效 1有效（收益）  2兑换
     */
    public Integer getStatus() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>exchange.exchange_log.interests</code>. 权益
     */
    public void setInterests(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>exchange.exchange_log.interests</code>. 权益
     */
    public BigDecimal getInterests() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>exchange.exchange_log.exchange_type</code>. 兑换方式：0  油卡 1微信红包
     */
    public void setExchangeType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>exchange.exchange_log.exchange_type</code>. 兑换方式：0  油卡 1微信红包
     */
    public Integer getExchangeType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>exchange.exchange_log.time</code>. 状态的操作时间
     */
    public void setTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>exchange.exchange_log.time</code>. 状态的操作时间
     */
    public Timestamp getTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>exchange.exchange_log.exchange_id</code>. 兑换记录的id
     */
    public void setExchangeId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>exchange.exchange_log.exchange_id</code>. 兑换记录的id
     */
    public String getExchangeId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>exchange.exchange_log.user_id</code>. 用户的id
     */
    public void setUserId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>exchange.exchange_log.user_id</code>. 用户的id
     */
    public String getUserId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Integer, BigDecimal, Integer, Timestamp, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Integer, BigDecimal, Integer, Timestamp, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ExchangeLog.EXCHANGE_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ExchangeLog.EXCHANGE_LOG.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ExchangeLog.EXCHANGE_LOG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return ExchangeLog.EXCHANGE_LOG.INTERESTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ExchangeLog.EXCHANGE_LOG.EXCHANGE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ExchangeLog.EXCHANGE_LOG.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ExchangeLog.EXCHANGE_LOG.EXCHANGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ExchangeLog.EXCHANGE_LOG.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getInterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getExchangeType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getExchangeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getInterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getExchangeType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getExchangeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord value2(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord value3(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord value4(BigDecimal value) {
        setInterests(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord value5(Integer value) {
        setExchangeType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord value6(Timestamp value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord value7(String value) {
        setExchangeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord value8(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeLogRecord values(String value1, String value2, Integer value3, BigDecimal value4, Integer value5, Timestamp value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExchangeLogRecord
     */
    public ExchangeLogRecord() {
        super(ExchangeLog.EXCHANGE_LOG);
    }

    /**
     * Create a detached, initialised ExchangeLogRecord
     */
    public ExchangeLogRecord(String id, String mobile, Integer status, BigDecimal interests, Integer exchangeType, Timestamp time, String exchangeId, String userId) {
        super(ExchangeLog.EXCHANGE_LOG);

        set(0, id);
        set(1, mobile);
        set(2, status);
        set(3, interests);
        set(4, exchangeType);
        set(5, time);
        set(6, exchangeId);
        set(7, userId);
    }
}
