/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model.tables.records;


import com.walker.jooq.jooqdemo.model.tables.OilCard;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 油卡
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OilCardRecord extends UpdatableRecordImpl<OilCardRecord> implements Record10<String, String, String, String, String, String, Byte, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -16283191;

    /**
     * Setter for <code>exchange.oil_card.id</code>. 主键UUID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>exchange.oil_card.id</code>. 主键UUID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>exchange.oil_card.card_no</code>. 卡号
     */
    public void setCardNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>exchange.oil_card.card_no</code>. 卡号
     */
    public String getCardNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>exchange.oil_card.card_password</code>. 卡密
     */
    public void setCardPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>exchange.oil_card.card_password</code>. 卡密
     */
    public String getCardPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>exchange.oil_card.money</code>. 金额
     */
    public void setMoney(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>exchange.oil_card.money</code>. 金额
     */
    public String getMoney() {
        return (String) get(3);
    }

    /**
     * Setter for <code>exchange.oil_card.company</code>. 所属公司
     */
    public void setCompany(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>exchange.oil_card.company</code>. 所属公司
     */
    public String getCompany() {
        return (String) get(4);
    }

    /**
     * Setter for <code>exchange.oil_card.batch</code>. 批次
     */
    public void setBatch(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>exchange.oil_card.batch</code>. 批次
     */
    public String getBatch() {
        return (String) get(5);
    }

    /**
     * Setter for <code>exchange.oil_card.status</code>. 状态：0-未兑换 1-已兑换
     */
    public void setStatus(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>exchange.oil_card.status</code>. 状态：0-未兑换 1-已兑换
     */
    public Byte getStatus() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>exchange.oil_card.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>exchange.oil_card.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>exchange.oil_card.release_time</code>. 发放时间
     */
    public void setReleaseTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>exchange.oil_card.release_time</code>. 发放时间
     */
    public Timestamp getReleaseTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>exchange.oil_card.expire_time</code>. 过期时间
     */
    public void setExpireTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>exchange.oil_card.expire_time</code>. 过期时间
     */
    public Timestamp getExpireTime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, Byte, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, Byte, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OilCard.OIL_CARD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OilCard.OIL_CARD.CARD_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OilCard.OIL_CARD.CARD_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OilCard.OIL_CARD.MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OilCard.OIL_CARD.COMPANY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OilCard.OIL_CARD.BATCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return OilCard.OIL_CARD.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return OilCard.OIL_CARD.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return OilCard.OIL_CARD.RELEASE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return OilCard.OIL_CARD.EXPIRE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCardPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCompany();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getBatch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getReleaseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCardPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCompany();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBatch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getReleaseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value2(String value) {
        setCardNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value3(String value) {
        setCardPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value4(String value) {
        setMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value5(String value) {
        setCompany(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value6(String value) {
        setBatch(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value7(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value8(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value9(Timestamp value) {
        setReleaseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord value10(Timestamp value) {
        setExpireTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OilCardRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Byte value7, Timestamp value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OilCardRecord
     */
    public OilCardRecord() {
        super(OilCard.OIL_CARD);
    }

    /**
     * Create a detached, initialised OilCardRecord
     */
    public OilCardRecord(String id, String cardNo, String cardPassword, String money, String company, String batch, Byte status, Timestamp createTime, Timestamp releaseTime, Timestamp expireTime) {
        super(OilCard.OIL_CARD);

        set(0, id);
        set(1, cardNo);
        set(2, cardPassword);
        set(3, money);
        set(4, company);
        set(5, batch);
        set(6, status);
        set(7, createTime);
        set(8, releaseTime);
        set(9, expireTime);
    }
}
