/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model.tables.records;


import com.walker.jooq.jooqdemo.model.tables.UserWhite;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 领卡人白名单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserWhiteRecord extends UpdatableRecordImpl<UserWhiteRecord> implements Record12<String, String, String, String, BigDecimal, BigDecimal, Timestamp, Timestamp, Byte, Byte, Timestamp, String> {

    private static final long serialVersionUID = -657039574;

    /**
     * Setter for <code>exchange.user_white.id</code>. 主键UUID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>exchange.user_white.id</code>. 主键UUID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>exchange.user_white.mobile</code>. 手机号
     */
    public void setMobile(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>exchange.user_white.mobile</code>. 手机号
     */
    public String getMobile() {
        return (String) get(1);
    }

    /**
     * Setter for <code>exchange.user_white.name</code>. 姓名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>exchange.user_white.name</code>. 姓名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>exchange.user_white.interests</code>. 权益
     */
    public void setInterests(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>exchange.user_white.interests</code>. 权益
     */
    public String getInterests() {
        return (String) get(3);
    }

    /**
     * Setter for <code>exchange.user_white.original_interests</code>. 原始权益-只读，不能修改
     */
    public void setOriginalInterests(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>exchange.user_white.original_interests</code>. 原始权益-只读，不能修改
     */
    public BigDecimal getOriginalInterests() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>exchange.user_white.actual_interests</code>. 实际到账权益
     */
    public void setActualInterests(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>exchange.user_white.actual_interests</code>. 实际到账权益
     */
    public BigDecimal getActualInterests() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>exchange.user_white.create_time</code>. 发放时间
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>exchange.user_white.create_time</code>. 发放时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>exchange.user_white.expire_time</code>. 失效时间
     */
    public void setExpireTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>exchange.user_white.expire_time</code>. 失效时间
     */
    public Timestamp getExpireTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>exchange.user_white.status</code>. 权益状态：0-失效，1-收益（有效），2兑换
     */
    public void setStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>exchange.user_white.status</code>. 权益状态：0-失效，1-收益（有效），2兑换
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>exchange.user_white.exchange_status</code>. 兑换状态：0-未兑换，1-已兑换
     */
    public void setExchangeStatus(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>exchange.user_white.exchange_status</code>. 兑换状态：0-未兑换，1-已兑换
     */
    public Byte getExchangeStatus() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>exchange.user_white.exchange_time</code>. 兑换时间
     */
    public void setExchangeTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>exchange.user_white.exchange_time</code>. 兑换时间
     */
    public Timestamp getExchangeTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>exchange.user_white.parent_id</code>. 父权益id
     */
    public void setParentId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>exchange.user_white.parent_id</code>. 父权益id
     */
    public String getParentId() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, BigDecimal, BigDecimal, Timestamp, Timestamp, Byte, Byte, Timestamp, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, BigDecimal, BigDecimal, Timestamp, Timestamp, Byte, Byte, Timestamp, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserWhite.USER_WHITE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserWhite.USER_WHITE.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserWhite.USER_WHITE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserWhite.USER_WHITE.INTERESTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return UserWhite.USER_WHITE.ORIGINAL_INTERESTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return UserWhite.USER_WHITE.ACTUAL_INTERESTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return UserWhite.USER_WHITE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return UserWhite.USER_WHITE.EXPIRE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return UserWhite.USER_WHITE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return UserWhite.USER_WHITE.EXCHANGE_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return UserWhite.USER_WHITE.EXCHANGE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return UserWhite.USER_WHITE.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getInterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getOriginalInterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getActualInterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getExchangeStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getExchangeTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getOriginalInterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getActualInterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getExchangeStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getExchangeTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value2(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value4(String value) {
        setInterests(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value5(BigDecimal value) {
        setOriginalInterests(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value6(BigDecimal value) {
        setActualInterests(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value8(Timestamp value) {
        setExpireTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value9(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value10(Byte value) {
        setExchangeStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value11(Timestamp value) {
        setExchangeTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord value12(String value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserWhiteRecord values(String value1, String value2, String value3, String value4, BigDecimal value5, BigDecimal value6, Timestamp value7, Timestamp value8, Byte value9, Byte value10, Timestamp value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserWhiteRecord
     */
    public UserWhiteRecord() {
        super(UserWhite.USER_WHITE);
    }

    /**
     * Create a detached, initialised UserWhiteRecord
     */
    public UserWhiteRecord(String id, String mobile, String name, String interests, BigDecimal originalInterests, BigDecimal actualInterests, Timestamp createTime, Timestamp expireTime, Byte status, Byte exchangeStatus, Timestamp exchangeTime, String parentId) {
        super(UserWhite.USER_WHITE);

        set(0, id);
        set(1, mobile);
        set(2, name);
        set(3, interests);
        set(4, originalInterests);
        set(5, actualInterests);
        set(6, createTime);
        set(7, expireTime);
        set(8, status);
        set(9, exchangeStatus);
        set(10, exchangeTime);
        set(11, parentId);
    }
}
