/*
 * This file is generated by jOOQ.
 */
package com.walker.jooq.jooqdemo.model.tables.records;


import com.walker.jooq.jooqdemo.model.tables.WxExchange;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 微信提现表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WxExchangeRecord extends UpdatableRecordImpl<WxExchangeRecord> implements Record14<String, String, String, Timestamp, String, String, BigDecimal, Double, Integer, String, Timestamp, String, Double, String> {

    private static final long serialVersionUID = 147656579;

    /**
     * Setter for <code>exchange.wx_exchange.id</code>. uuid
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.id</code>. uuid
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>exchange.wx_exchange.order_no</code>. 微信订单号 对应payment_no
     */
    public void setOrderNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.order_no</code>. 微信订单号 对应payment_no
     */
    public String getOrderNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>exchange.wx_exchange.open_id</code>. 用户对应的open_id
     */
    public void setOpenId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.open_id</code>. 用户对应的open_id
     */
    public String getOpenId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>exchange.wx_exchange.create_time</code>. 兑换时间
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.create_time</code>. 兑换时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>exchange.wx_exchange.money</code>. 兑换金额
     */
    public void setMoney(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.money</code>. 兑换金额
     */
    public String getMoney() {
        return (String) get(4);
    }

    /**
     * Setter for <code>exchange.wx_exchange.discount_money</code>. 折扣后金额
     */
    public void setDiscountMoney(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.discount_money</code>. 折扣后金额
     */
    public String getDiscountMoney() {
        return (String) get(5);
    }

    /**
     * Setter for <code>exchange.wx_exchange.service_charge</code>. 手续费
     */
    public void setServiceCharge(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.service_charge</code>. 手续费
     */
    public BigDecimal getServiceCharge() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>exchange.wx_exchange.cash_discount</code>. 微信提现折扣
     */
    public void setCashDiscount(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.cash_discount</code>. 微信提现折扣
     */
    public Double getCashDiscount() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>exchange.wx_exchange.status</code>. 状态 0失败 1成功
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.status</code>. 状态 0失败 1成功
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>exchange.wx_exchange.user_id</code>. 用户id
     */
    public void setUserId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.user_id</code>. 用户id
     */
    public String getUserId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>exchange.wx_exchange.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>exchange.wx_exchange.partner_trade_no</code>. 商户转账订单号
     */
    public void setPartnerTradeNo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.partner_trade_no</code>. 商户转账订单号
     */
    public String getPartnerTradeNo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>exchange.wx_exchange.service_charge_discount</code>. 手续费折扣
     */
    public void setServiceChargeDiscount(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.service_charge_discount</code>. 手续费折扣
     */
    public Double getServiceChargeDiscount() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>exchange.wx_exchange.error_info</code>. 失败原因
     */
    public void setErrorInfo(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>exchange.wx_exchange.error_info</code>. 失败原因
     */
    public String getErrorInfo() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, Timestamp, String, String, BigDecimal, Double, Integer, String, Timestamp, String, Double, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, Timestamp, String, String, BigDecimal, Double, Integer, String, Timestamp, String, Double, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return WxExchange.WX_EXCHANGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WxExchange.WX_EXCHANGE.ORDER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WxExchange.WX_EXCHANGE.OPEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return WxExchange.WX_EXCHANGE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WxExchange.WX_EXCHANGE.MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return WxExchange.WX_EXCHANGE.DISCOUNT_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return WxExchange.WX_EXCHANGE.SERVICE_CHARGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return WxExchange.WX_EXCHANGE.CASH_DISCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return WxExchange.WX_EXCHANGE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return WxExchange.WX_EXCHANGE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return WxExchange.WX_EXCHANGE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return WxExchange.WX_EXCHANGE.PARTNER_TRADE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return WxExchange.WX_EXCHANGE.SERVICE_CHARGE_DISCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return WxExchange.WX_EXCHANGE.ERROR_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDiscountMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getServiceCharge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getCashDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getPartnerTradeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component13() {
        return getServiceChargeDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getErrorInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDiscountMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getServiceCharge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getCashDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPartnerTradeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getServiceChargeDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getErrorInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value2(String value) {
        setOrderNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value3(String value) {
        setOpenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value5(String value) {
        setMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value6(String value) {
        setDiscountMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value7(BigDecimal value) {
        setServiceCharge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value8(Double value) {
        setCashDiscount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value10(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value11(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value12(String value) {
        setPartnerTradeNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value13(Double value) {
        setServiceChargeDiscount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord value14(String value) {
        setErrorInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxExchangeRecord values(String value1, String value2, String value3, Timestamp value4, String value5, String value6, BigDecimal value7, Double value8, Integer value9, String value10, Timestamp value11, String value12, Double value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WxExchangeRecord
     */
    public WxExchangeRecord() {
        super(WxExchange.WX_EXCHANGE);
    }

    /**
     * Create a detached, initialised WxExchangeRecord
     */
    public WxExchangeRecord(String id, String orderNo, String openId, Timestamp createTime, String money, String discountMoney, BigDecimal serviceCharge, Double cashDiscount, Integer status, String userId, Timestamp updateTime, String partnerTradeNo, Double serviceChargeDiscount, String errorInfo) {
        super(WxExchange.WX_EXCHANGE);

        set(0, id);
        set(1, orderNo);
        set(2, openId);
        set(3, createTime);
        set(4, money);
        set(5, discountMoney);
        set(6, serviceCharge);
        set(7, cashDiscount);
        set(8, status);
        set(9, userId);
        set(10, updateTime);
        set(11, partnerTradeNo);
        set(12, serviceChargeDiscount);
        set(13, errorInfo);
    }
}
